dcsaorg/DCSA-Core

- pom.xml
- src/main/java/org/dcsa/core/extendedrequest/ExtendedRequest.java
- src/main/java/org/dcsa/core/extendedrequest/Filter.java
- src/main/java/org/dcsa/core/util/ReflectUtility.java
Bump version
Make sure the Ignore parameter supports the extended event class
> Make sure Ignored fields supports the extended Event model

- pom.xml
- src/main/java/org/dcsa/core/repository/ExtendedRepositoryImpl.java
Handle Database Intervals as Java String
Bump Version
> Handle database intervals

- .run/dcsa_tnt.run.xml
- pom.xml
- src/main/java/org/dcsa/core/controller/BaseController.java
- src/main/java/org/dcsa/core/extendedrequest/ExtendedParameters.java
- src/main/java/org/dcsa/core/extendedrequest/ExtendedRequest.java
- src/main/java/org/dcsa/core/extendedrequest/Filter.java
- src/main/java/org/dcsa/core/extendedrequest/FilterItem.java
- src/main/java/org/dcsa/core/service/BaseService.java
- src/main/java/org/dcsa/core/service/impl/BaseServiceImpl.java
- src/main/java/org/dcsa/core/util/ReflectUtility.java
Bump version to 0.7.0
Bump Spring Boot to 2.3.5
General cleanup
Change naming: save -> create when Posting
Better filtering options when filtering on Dates (and DateTime)
> Multiple updates

- pom.xml
- src/main/java/org/dcsa/core/util/ValidationUtils.java
Bump Core version
Add validation rule for VesselIMONumber to be reused between projects
> Add validation rules to Core

- .github/workflows/publishPRSnapshot.yml
- .github/workflows/runTNTTests.yml
- pom.xml
- src/main/java/org/dcsa/core/security/SecurityConfig.java
CSRF was still enabled when authentication was disabled. This was causing POST requests to fail.
> Disable CSRF when auth is disabled

- pom.xml
- src/main/java/org/dcsa/core/security/SecurityConfig.java
> SecurityConfig: Log whether security is enabled

- pom.xml
- src/main/java/org/dcsa/core/extendedrequest/ExtendedRequest.java
- src/main/java/org/dcsa/core/repository/ExtendedRepositoryImpl.java
> Bump spring-boot to 2.4.2

- .github/workflows/runTNTTests.yml
> CI: Point TNT test to TNT master again

- pom.xml
> Bump core to 0.7.10

- pom.xml
- src/main/java/org/dcsa/core/util/ReflectUtility.java
- src/test/java/org/dcsa/core/models/Order.java
> Fix invalid JSON name with `@JsonProperty.USE_DEFAULT_NAME`

- pom.xml
- src/main/java/org/dcsa/core/repository/ExtendedRepositoryImpl.java
> Fix NPE when setting Enums with Null as value

- .github/workflows/runTNTTests.yml
> CI: Set CALLBACK_URI during tests

- pom.xml
- src/main/java/org/dcsa/core/extendedrequest/QueryFields.java
- src/main/java/org/dcsa/core/model/ForeignKey.java
- src/main/java/org/dcsa/core/query/impl/DefaultDBEntityAnalysisBuilder.java
- src/main/java/org/dcsa/core/repository/ExtendedRepositoryImpl.java
- src/main/java/org/dcsa/core/repository/RowMapper.java
- src/test/java/org/dcsa/core/ExtendedRequestTest.java
- src/test/java/org/dcsa/core/RowMapperTest.java
- src/test/java/org/dcsa/core/models/AbstractCustomerBook.java
- src/test/java/org/dcsa/core/models/City.java
- src/test/java/org/dcsa/core/models/combined/CityCustomerBook.java
- src/test/java/org/dcsa/core/models/combined/CustomerBook.java
- src/test/java/org/dcsa/core/models/combined/CustomerWithForeignKeyAddresses.java
- src/test/java/org/dcsa/core/models/combined/ExtendedOrder.java
- src/test/java/org/dcsa/core/stub/StubColumnMetadata.java
- src/test/java/org/dcsa/core/stub/StubRow.java
- src/test/java/org/dcsa/core/stub/StubRowMetadata.java
Support one-to-one relations using @ForeignKey on models.
> Add one-to-one relation

- .github/workflows/runTNTTests.yml
> Renamed dcsa.tag to dcsa.core.tag

- pom.xml
- src/main/java/org/dcsa/core/extendedrequest/QueryFields.java
- src/main/java/org/dcsa/core/query/impl/DefaultDBEntityAnalysisBuilder.java
- src/main/java/org/dcsa/core/repository/RowMapper.java
- src/test/java/org/dcsa/core/ExtendedRequestTest.java
- src/test/java/org/dcsa/core/RowMapperTest.java
Discovered while working on upgrading OVS.
> Fix mapping bugs

- src/main/java/org/dcsa/core/extendedrequest/QueryParameterParser.java
> Fix NPE on empty filter

- pom.xml
- src/main/java/org/dcsa/core/security/SecurityConfig.java
> DDT-16: Punch a hole in the security filter for notifications

- src/main/java/org/dcsa/core/extendedrequest/ExtendedParameters.java
> Fix inline documentation for reservedParameters

- src/main/java/org/dcsa/core/configuration/DCSACoreConfiguration.java
> Support Proxy headers

- pom.xml
> Bump DCSA-Core to 0.8.11

- pom.xml
- src/main/java/org/dcsa/core/security/SecurityConfig.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-253
> Added actuator and excluded health endpoint from auth.

- src/main/java/org/dcsa/core/util/ValidationUtils.java
- src/main/java/org/dcsa/core/validator/ValidVesselIMONumber.java
- src/main/java/org/dcsa/core/validator/VesselIMONumberValidator.java
> Make a `@ValidVesselIMONumber` validator

- pom.xml
- src/main/java/org/dcsa/core/util/MappingUtils.java
- src/main/java/org/dcsa/core/util/ReflectUtility.java
> Ignore synthetic fields everywhere

- src/main/java/org/dcsa/core/exception/handler/GlobalExceptionHandler.java
> Pass causing exception to DatabaseException

- pom.xml
- src/main/java/org/dcsa/core/query/impl/DefaultDBEntityAnalysisBuilder.java
> Fix NPE in getJoinDescriptor

- src/main/java/org/dcsa/core/controller/filter/ApiVersionHeaderFilter.java
> DDT-652 adds API-Version Response header

- .github/workflows/runTNTTests.yml
- pom.xml
> Final BKG 1.0.0

- src/main/java/org/dcsa/core/validator/DateRange.java
> Add missing attributes to DateRange

- src/main/java/org/dcsa/core/validator/RequiredIfTrue.java
- src/main/java/org/dcsa/core/validator/RequiredIfTrueValidator.java
- src/test/java/org/dcsa/core/validator/RequiredIfTrueValidatorTest.java
Intended usage:
```java
@RequiredIfTrue(isFieldReferenceRequired = "isImportLicenseRequired", fieldReference = "importLicenseReference")
public class ClassName {
@NotNull(message = "The attribute isImportLicenseRequired is required.")
protected Boolean isImportLicenseRequired;
@Size(max = 35, message = "The attribute importLicenseReference has a max size of 35.")
protected String importLicenseReference;
}
```
> DDT-752: RequiredIfTrue validator annotation

- src/main/java/org/dcsa/core/extendedrequest/testsupport/ExtendedRequestVerifier.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/ExtendedRequestVerifierImpl.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/MockBindMarker.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/MockBindMarkers.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/MockR2dbcDialect.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/TriFunction.java
- src/test/java/org/dcsa/core/ExtendedRequestTest.java
- src/test/java/org/dcsa/core/repository/RowMapperTest.java
> DDT-828: Provide test framework for testing custom ExtendedRequest classes

- src/main/java/org/dcsa/core/exception/ConcreteRequestErrorMessageException.java
- src/main/java/org/dcsa/core/exception/ConflictException.java
- src/main/java/org/dcsa/core/exception/handler/GlobalExceptionHandler.java
> Ensure Data Integrition exceptions are mapped to 409 Conflict by default

- src/main/java/org/dcsa/core/exception/handler/GlobalExceptionHandler.java
- src/test/java/org/dcsa/core/exception/handler/GlobalExceptionHandlerTest.java
- src/test/java/org/dcsa/core/exception/handler/TestPoJo.java
> DDT-888 refactored GlobalExceptionHandler to support chaining

- pom.xml
- src/main/java/org/dcsa/core/extendedrequest/JoinDescriptor.java
- src/main/java/org/dcsa/core/extendedrequest/JoinedWithModelBasedJoinDescriptor.java
- src/main/java/org/dcsa/core/extendedrequest/QueryFields.java
- src/main/java/org/dcsa/core/extendedrequest/TableAndJoins.java
- src/main/java/org/dcsa/core/query/DBEntityAnalysis.java
- src/main/java/org/dcsa/core/query/impl/AbstractDBEntityAnalysisBuilder.java
- src/main/java/org/dcsa/core/query/impl/DefaultDBEntityAnalysisBuilder.java
- src/main/java/org/dcsa/core/query/impl/SimpleJoinDescriptor.java
- src/main/java/org/dcsa/core/util/ReflectUtility.java
We need a newer version of spring boot to support more complicated
JOINs, which is in turn necessary to solve DDT-929.
> DDT-929 [1/?]: Update spring boot to 2.6.4

- src/main/java/org/dcsa/core/exception/ConcreteRequestErrorMessageException.java
- src/main/java/org/dcsa/core/extendedrequest/ExtendedParameters.java
- src/main/java/org/dcsa/core/extendedrequest/Pagination.java
> DDT-1014: Validate limit parameters better

- src/main/java/org/dcsa/core/extendedrequest/ExtendedRequest.java
> Remove now unused code

- src/main/java/org/dcsa/core/extendedrequest/ExtendedRequest.java
- src/main/java/org/dcsa/core/extendedrequest/Pagination.java
- src/main/java/org/dcsa/core/extendedrequest/ParseState.java
- src/main/java/org/dcsa/core/extendedrequest/QueryParameterParser.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/ExtendedRequestVerifier.java
- src/main/java/org/dcsa/core/extendedrequest/testsupport/ExtendedRequestVerifierImpl.java
- src/test/java/org/dcsa/core/ExtendedRequestTest.java
> DDT-1056: Correct the cursor parsing code

- pom.xml
> Bump DCSA-Core
